/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSatScopeProvider extends DelegatingScopeProvider {
}
