/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.dimacs;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commentaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.dimacs.Commentaire#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.dimacs.DimacsPackage#getCommentaire()
 * @model
 * @generated
 */
public interface Commentaire extends EObject
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see org.xtext.example.mydsl.dimacs.DimacsPackage#getCommentaire_Content()
   * @model
   * @generated
   */
  String getContent();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.dimacs.Commentaire#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  void setContent(String value);

} // Commentaire
