/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.dimacs;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.dimacs.DimacsFactory
 * @model kind="package"
 * @generated
 */
public interface DimacsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dimacs";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Dimacs";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dimacs";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DimacsPackage eINSTANCE = org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dimacs.impl.CNFImpl <em>CNF</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dimacs.impl.CNFImpl
   * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getCNF()
   * @generated
   */
  int CNF = 0;

  /**
   * The feature id for the '<em><b>Comments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CNF__COMMENTS = 0;

  /**
   * The feature id for the '<em><b>Problem</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CNF__PROBLEM = 1;

  /**
   * The feature id for the '<em><b>Clauses</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CNF__CLAUSES = 2;

  /**
   * The number of structural features of the '<em>CNF</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CNF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dimacs.impl.CommentaireImpl <em>Commentaire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dimacs.impl.CommentaireImpl
   * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getCommentaire()
   * @generated
   */
  int COMMENTAIRE = 1;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMENTAIRE__CONTENT = 0;

  /**
   * The number of structural features of the '<em>Commentaire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMENTAIRE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dimacs.impl.LigneProblemeImpl <em>Ligne Probleme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dimacs.impl.LigneProblemeImpl
   * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getLigneProbleme()
   * @generated
   */
  int LIGNE_PROBLEME = 2;

  /**
   * The feature id for the '<em><b>Nb variables</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_PROBLEME__NB_VARIABLES = 0;

  /**
   * The feature id for the '<em><b>Nb clauses</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_PROBLEME__NB_CLAUSES = 1;

  /**
   * The number of structural features of the '<em>Ligne Probleme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_PROBLEME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dimacs.impl.LigneClauseImpl <em>Ligne Clause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dimacs.impl.LigneClauseImpl
   * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getLigneClause()
   * @generated
   */
  int LIGNE_CLAUSE = 3;

  /**
   * The feature id for the '<em><b>Litteraux</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_CLAUSE__LITTERAUX = 0;

  /**
   * The number of structural features of the '<em>Ligne Clause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_CLAUSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dimacs.impl.litteralImpl <em>litteral</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dimacs.impl.litteralImpl
   * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getlitteral()
   * @generated
   */
  int LITTERAL = 4;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITTERAL__VAL = 0;

  /**
   * The number of structural features of the '<em>litteral</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITTERAL_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dimacs.CNF <em>CNF</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CNF</em>'.
   * @see org.xtext.example.mydsl.dimacs.CNF
   * @generated
   */
  EClass getCNF();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.dimacs.CNF#getComments <em>Comments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Comments</em>'.
   * @see org.xtext.example.mydsl.dimacs.CNF#getComments()
   * @see #getCNF()
   * @generated
   */
  EReference getCNF_Comments();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.dimacs.CNF#getProblem <em>Problem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Problem</em>'.
   * @see org.xtext.example.mydsl.dimacs.CNF#getProblem()
   * @see #getCNF()
   * @generated
   */
  EReference getCNF_Problem();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.dimacs.CNF#getClauses <em>Clauses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clauses</em>'.
   * @see org.xtext.example.mydsl.dimacs.CNF#getClauses()
   * @see #getCNF()
   * @generated
   */
  EReference getCNF_Clauses();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dimacs.Commentaire <em>Commentaire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Commentaire</em>'.
   * @see org.xtext.example.mydsl.dimacs.Commentaire
   * @generated
   */
  EClass getCommentaire();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.dimacs.Commentaire#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see org.xtext.example.mydsl.dimacs.Commentaire#getContent()
   * @see #getCommentaire()
   * @generated
   */
  EAttribute getCommentaire_Content();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dimacs.LigneProbleme <em>Ligne Probleme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligne Probleme</em>'.
   * @see org.xtext.example.mydsl.dimacs.LigneProbleme
   * @generated
   */
  EClass getLigneProbleme();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.dimacs.LigneProbleme#getNb_variables <em>Nb variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Nb variables</em>'.
   * @see org.xtext.example.mydsl.dimacs.LigneProbleme#getNb_variables()
   * @see #getLigneProbleme()
   * @generated
   */
  EAttribute getLigneProbleme_Nb_variables();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.dimacs.LigneProbleme#getNb_clauses <em>Nb clauses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Nb clauses</em>'.
   * @see org.xtext.example.mydsl.dimacs.LigneProbleme#getNb_clauses()
   * @see #getLigneProbleme()
   * @generated
   */
  EAttribute getLigneProbleme_Nb_clauses();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dimacs.LigneClause <em>Ligne Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligne Clause</em>'.
   * @see org.xtext.example.mydsl.dimacs.LigneClause
   * @generated
   */
  EClass getLigneClause();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.dimacs.LigneClause#getLitteraux <em>Litteraux</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Litteraux</em>'.
   * @see org.xtext.example.mydsl.dimacs.LigneClause#getLitteraux()
   * @see #getLigneClause()
   * @generated
   */
  EReference getLigneClause_Litteraux();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dimacs.litteral <em>litteral</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>litteral</em>'.
   * @see org.xtext.example.mydsl.dimacs.litteral
   * @generated
   */
  EClass getlitteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.dimacs.litteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.mydsl.dimacs.litteral#getVal()
   * @see #getlitteral()
   * @generated
   */
  EAttribute getlitteral_Val();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DimacsFactory getDimacsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dimacs.impl.CNFImpl <em>CNF</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dimacs.impl.CNFImpl
     * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getCNF()
     * @generated
     */
    EClass CNF = eINSTANCE.getCNF();

    /**
     * The meta object literal for the '<em><b>Comments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CNF__COMMENTS = eINSTANCE.getCNF_Comments();

    /**
     * The meta object literal for the '<em><b>Problem</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CNF__PROBLEM = eINSTANCE.getCNF_Problem();

    /**
     * The meta object literal for the '<em><b>Clauses</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CNF__CLAUSES = eINSTANCE.getCNF_Clauses();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dimacs.impl.CommentaireImpl <em>Commentaire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dimacs.impl.CommentaireImpl
     * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getCommentaire()
     * @generated
     */
    EClass COMMENTAIRE = eINSTANCE.getCommentaire();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMENTAIRE__CONTENT = eINSTANCE.getCommentaire_Content();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dimacs.impl.LigneProblemeImpl <em>Ligne Probleme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dimacs.impl.LigneProblemeImpl
     * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getLigneProbleme()
     * @generated
     */
    EClass LIGNE_PROBLEME = eINSTANCE.getLigneProbleme();

    /**
     * The meta object literal for the '<em><b>Nb variables</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIGNE_PROBLEME__NB_VARIABLES = eINSTANCE.getLigneProbleme_Nb_variables();

    /**
     * The meta object literal for the '<em><b>Nb clauses</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIGNE_PROBLEME__NB_CLAUSES = eINSTANCE.getLigneProbleme_Nb_clauses();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dimacs.impl.LigneClauseImpl <em>Ligne Clause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dimacs.impl.LigneClauseImpl
     * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getLigneClause()
     * @generated
     */
    EClass LIGNE_CLAUSE = eINSTANCE.getLigneClause();

    /**
     * The meta object literal for the '<em><b>Litteraux</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIGNE_CLAUSE__LITTERAUX = eINSTANCE.getLigneClause_Litteraux();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dimacs.impl.litteralImpl <em>litteral</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dimacs.impl.litteralImpl
     * @see org.xtext.example.mydsl.dimacs.impl.DimacsPackageImpl#getlitteral()
     * @generated
     */
    EClass LITTERAL = eINSTANCE.getlitteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITTERAL__VAL = eINSTANCE.getlitteral_Val();

  }

} //DimacsPackage
