/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.dimacs;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ligne Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.dimacs.LigneClause#getLitteraux <em>Litteraux</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.dimacs.DimacsPackage#getLigneClause()
 * @model
 * @generated
 */
public interface LigneClause extends EObject
{
  /**
   * Returns the value of the '<em><b>Litteraux</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.dimacs.litteral}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Litteraux</em>' containment reference list.
   * @see org.xtext.example.mydsl.dimacs.DimacsPackage#getLigneClause_Litteraux()
   * @model containment="true"
   * @generated
   */
  EList<litteral> getLitteraux();

} // LigneClause
