/*
 * generated by Xtext 2.19.0
 */
package fr.gjouneau.dsl.sat.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSatScopeProvider extends DelegatingScopeProvider {
}
