/**
 * generated by Xtext 2.19.0
 */
package fr.m1sif.dsl.ui;

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SatUiModule /* implements AbstractSatUiModule  */{
}
