/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.sat;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sat.Model#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sat.SatPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' containment reference.
   * @see #setModel(Expression)
   * @see org.xtext.example.mydsl.sat.SatPackage#getModel_Model()
   * @model containment="true"
   * @generated
   */
  Expression getModel();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sat.Model#getModel <em>Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' containment reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Expression value);

} // Model
