<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="satdsl" nsURI="http://www.example.org/satdsl" nsPrefix="satdsl">
  <eClassifiers xsi:type="ecore:EClass" name="Expression" instanceTypeName="Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binexpr" eType="#//BinExpr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unexpr" eType="#//UnExpr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atom" eType="#//Literal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinExpr" instanceTypeName="Binop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="2"
        upperBound="2" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnExpr" instanceTypeName="Unop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="AND" eSuperTypes="#//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="NOT" eSuperTypes="#//UnExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="NAND" eSuperTypes="#//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMPLIES" eSuperTypes="#//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="BIIMPLIES" eSuperTypes="#//BinExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="const" eType="#//Const"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atom" eType="#//Atom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Const">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
