/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui;

import org.xtext.example.sat.ui.internal.SatActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SatExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SatActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SatActivator activator = SatActivator.getInstance();
		return activator != null ? activator.getInjector(SatActivator.ORG_XTEXT_EXAMPLE_MYDSL_SAT) : null;
	}

}
