/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.DimacsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DimacsStandaloneSetup extends DimacsStandaloneSetupGenerated {
  public static void doSetup() {
    new DimacsStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
