/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.mydsl.sat.Expression
import org.xtext.example.mydsl.generator.SatGenerator

@ExtendWith(InjectionExtension)
@InjectWith(SatInjectorProvider)
class SatParsingTest {
	@Inject
	ParseHelper<Expression> parseHelper
	// ParseHelper<SAT> parseHelper
	
	
	// Files.writer(String, new File(String filename));
	
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			A v B => C
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		println("model=" + result)
	}
	
	@Test
	def void test1(){
		val result = parseHelper.parse('''
			(A v ! B) ^ (B v C v ! A)
		''')
		Assertions.assertTrue(Utils.dimacsPrinter(result).equals("1 -111 0\n1 11 -1111 0\n"));
	}
}
