/**
 * generated by Xtext 2.19.0
 */
package fr.gjouneau.dsl.sat.sat;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.gjouneau.dsl.sat.sat.SatFactory
 * @model kind="package"
 * @generated
 */
public interface SatPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sat";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.gjouneau.fr/dsl/sat/Sat";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sat";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SatPackage eINSTANCE = fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.gjouneau.dsl.sat.sat.impl.ModelSATImpl <em>Model SAT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.gjouneau.dsl.sat.sat.impl.ModelSATImpl
   * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getModelSAT()
   * @generated
   */
  int MODEL_SAT = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_SAT__EXPRESSION = 0;

  /**
   * The number of structural features of the '<em>Model SAT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_SAT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.gjouneau.dsl.sat.sat.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.gjouneau.dsl.sat.sat.impl.ExpressionImpl
   * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.gjouneau.dsl.sat.sat.impl.EquivImpl <em>Equiv</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.gjouneau.dsl.sat.sat.impl.EquivImpl
   * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getEquiv()
   * @generated
   */
  int EQUIV = 2;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUIV__LHS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUIV__RHS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Equiv</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.gjouneau.dsl.sat.sat.impl.ImpliesImpl <em>Implies</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.gjouneau.dsl.sat.sat.impl.ImpliesImpl
   * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getImplies()
   * @generated
   */
  int IMPLIES = 3;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIES__LHS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIES__RHS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Implies</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIES_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.gjouneau.dsl.sat.sat.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.gjouneau.dsl.sat.sat.impl.OrImpl
   * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getOr()
   * @generated
   */
  int OR = 4;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LHS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RHS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.gjouneau.dsl.sat.sat.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.gjouneau.dsl.sat.sat.impl.AndImpl
   * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getAnd()
   * @generated
   */
  int AND = 5;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LHS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RHS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.gjouneau.dsl.sat.sat.impl.NandImpl <em>Nand</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.gjouneau.dsl.sat.sat.impl.NandImpl
   * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getNand()
   * @generated
   */
  int NAND = 6;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAND__LHS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAND__RHS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Nand</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.gjouneau.dsl.sat.sat.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.gjouneau.dsl.sat.sat.impl.NotImpl
   * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getNot()
   * @generated
   */
  int NOT = 7;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__EXPRESSION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.gjouneau.dsl.sat.sat.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.gjouneau.dsl.sat.sat.impl.VariableImpl
   * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link fr.gjouneau.dsl.sat.sat.ModelSAT <em>Model SAT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model SAT</em>'.
   * @see fr.gjouneau.dsl.sat.sat.ModelSAT
   * @generated
   */
  EClass getModelSAT();

  /**
   * Returns the meta object for the containment reference list '{@link fr.gjouneau.dsl.sat.sat.ModelSAT#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expression</em>'.
   * @see fr.gjouneau.dsl.sat.sat.ModelSAT#getExpression()
   * @see #getModelSAT()
   * @generated
   */
  EReference getModelSAT_Expression();

  /**
   * Returns the meta object for class '{@link fr.gjouneau.dsl.sat.sat.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link fr.gjouneau.dsl.sat.sat.Equiv <em>Equiv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equiv</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Equiv
   * @generated
   */
  EClass getEquiv();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.Equiv#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Equiv#getLhs()
   * @see #getEquiv()
   * @generated
   */
  EReference getEquiv_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.Equiv#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Equiv#getRhs()
   * @see #getEquiv()
   * @generated
   */
  EReference getEquiv_Rhs();

  /**
   * Returns the meta object for class '{@link fr.gjouneau.dsl.sat.sat.Implies <em>Implies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Implies</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Implies
   * @generated
   */
  EClass getImplies();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.Implies#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Implies#getLhs()
   * @see #getImplies()
   * @generated
   */
  EReference getImplies_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.Implies#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Implies#getRhs()
   * @see #getImplies()
   * @generated
   */
  EReference getImplies_Rhs();

  /**
   * Returns the meta object for class '{@link fr.gjouneau.dsl.sat.sat.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.Or#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Or#getLhs()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.Or#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Or#getRhs()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Rhs();

  /**
   * Returns the meta object for class '{@link fr.gjouneau.dsl.sat.sat.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see fr.gjouneau.dsl.sat.sat.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.And#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.And#getLhs()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.And#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.And#getRhs()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Rhs();

  /**
   * Returns the meta object for class '{@link fr.gjouneau.dsl.sat.sat.Nand <em>Nand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nand</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Nand
   * @generated
   */
  EClass getNand();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.Nand#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Nand#getLhs()
   * @see #getNand()
   * @generated
   */
  EReference getNand_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.Nand#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Nand#getRhs()
   * @see #getNand()
   * @generated
   */
  EReference getNand_Rhs();

  /**
   * Returns the meta object for class '{@link fr.gjouneau.dsl.sat.sat.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for the containment reference '{@link fr.gjouneau.dsl.sat.sat.Not#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Not#getExpression()
   * @see #getNot()
   * @generated
   */
  EReference getNot_Expression();

  /**
   * Returns the meta object for class '{@link fr.gjouneau.dsl.sat.sat.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link fr.gjouneau.dsl.sat.sat.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.gjouneau.dsl.sat.sat.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SatFactory getSatFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.gjouneau.dsl.sat.sat.impl.ModelSATImpl <em>Model SAT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.gjouneau.dsl.sat.sat.impl.ModelSATImpl
     * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getModelSAT()
     * @generated
     */
    EClass MODEL_SAT = eINSTANCE.getModelSAT();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL_SAT__EXPRESSION = eINSTANCE.getModelSAT_Expression();

    /**
     * The meta object literal for the '{@link fr.gjouneau.dsl.sat.sat.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.gjouneau.dsl.sat.sat.impl.ExpressionImpl
     * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link fr.gjouneau.dsl.sat.sat.impl.EquivImpl <em>Equiv</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.gjouneau.dsl.sat.sat.impl.EquivImpl
     * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getEquiv()
     * @generated
     */
    EClass EQUIV = eINSTANCE.getEquiv();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUIV__LHS = eINSTANCE.getEquiv_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUIV__RHS = eINSTANCE.getEquiv_Rhs();

    /**
     * The meta object literal for the '{@link fr.gjouneau.dsl.sat.sat.impl.ImpliesImpl <em>Implies</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.gjouneau.dsl.sat.sat.impl.ImpliesImpl
     * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getImplies()
     * @generated
     */
    EClass IMPLIES = eINSTANCE.getImplies();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPLIES__LHS = eINSTANCE.getImplies_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPLIES__RHS = eINSTANCE.getImplies_Rhs();

    /**
     * The meta object literal for the '{@link fr.gjouneau.dsl.sat.sat.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.gjouneau.dsl.sat.sat.impl.OrImpl
     * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LHS = eINSTANCE.getOr_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RHS = eINSTANCE.getOr_Rhs();

    /**
     * The meta object literal for the '{@link fr.gjouneau.dsl.sat.sat.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.gjouneau.dsl.sat.sat.impl.AndImpl
     * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LHS = eINSTANCE.getAnd_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RHS = eINSTANCE.getAnd_Rhs();

    /**
     * The meta object literal for the '{@link fr.gjouneau.dsl.sat.sat.impl.NandImpl <em>Nand</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.gjouneau.dsl.sat.sat.impl.NandImpl
     * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getNand()
     * @generated
     */
    EClass NAND = eINSTANCE.getNand();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAND__LHS = eINSTANCE.getNand_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAND__RHS = eINSTANCE.getNand_Rhs();

    /**
     * The meta object literal for the '{@link fr.gjouneau.dsl.sat.sat.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.gjouneau.dsl.sat.sat.impl.NotImpl
     * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT__EXPRESSION = eINSTANCE.getNot_Expression();

    /**
     * The meta object literal for the '{@link fr.gjouneau.dsl.sat.sat.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.gjouneau.dsl.sat.sat.impl.VariableImpl
     * @see fr.gjouneau.dsl.sat.sat.impl.SatPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

  }

} //SatPackage
