/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl1.MSatRuntimeModule;
import org.xtext.example.mydsl1.MSatStandaloneSetup;
import org.xtext.example.mydsl1.ide.MSatIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MSatIdeSetup extends MSatStandaloneSetup {
  @Override
  public Injector createInjector() {
    MSatRuntimeModule _mSatRuntimeModule = new MSatRuntimeModule();
    MSatIdeModule _mSatIdeModule = new MSatIdeModule();
    return Guice.createInjector(Modules2.mixin(_mSatRuntimeModule, _mSatIdeModule));
  }
}
