/*
 * generated by Xtext 2.19.0
 */
package projetDSL


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SATLStandaloneSetup extends SATLStandaloneSetupGenerated {

	def static void doSetup() {
		new SATLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
