/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui;

import org.xtext.example.mydsl.ui.AbstractSatUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SatUiModule extends AbstractSatUiModule {
  public SatUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
