/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.validation;

import org.xtext.example.mydsl.validation.AbstractSattValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SattValidator extends AbstractSattValidator {
}
