/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.SattlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SattlStandaloneSetup extends SattlStandaloneSetupGenerated {
  public static void doSetup() {
    new SattlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
