<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ModelSAT" nsURI="SAT" nsPrefix="SAT">
  <eClassifiers xsi:type="ecore:EClass" name="ModelSAT">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nand" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implies" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equiv" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
