<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SAT">
  <eClassifiers xsi:type="ecore:EClass" name="Formulae">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Binop"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Formulae_left"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Formulae_right"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Unop"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Formulae_middle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Atom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OR"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AND"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NAND"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IMPLIES"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BIIMPLIES"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NOT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ATOM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
