/**
 * generated by Xtext 2.19.0
 */
package m2ccs.dsl.satsv.mydsl.ide;

import m2ccs.dsl.satsv.mydsl.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
