/**
 * generated by Xtext 2.19.0
 */
package fr.gjouneau.dsl.sat.scoping;

import fr.gjouneau.dsl.sat.scoping.AbstractSatScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class SatScopeProvider extends AbstractSatScopeProvider {
}
