/*
 * generated by Xtext 2.19.0
 */
package projetDSL.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import projetDSL.ui.internal.ProjetDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SATLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ProjetDSLActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ProjetDSLActivator activator = ProjetDSLActivator.getInstance();
		return activator != null ? activator.getInjector(ProjetDSLActivator.PROJETDSL_SATL) : null;
	}

}
