/*
 * generated by Xtext 2.19.0
 */
package m2ccs.dsl.satsv.mydsl.ui.tests;

import com.google.inject.Injector;
import m2ccs.dsl.satsv.mydsl.ui.internal.MydslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("m2ccs.dsl.satsv.mydsl.MyDsl");
	}

}
