/*
 * generated by Xtext 2.19.0
 */
package fr.gjouneau.dsl.sat.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.gjouneau.dsl.sat.ide.contentassist.antlr.internal.InternalSatParser;
import fr.gjouneau.dsl.sat.services.SatGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class SatParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SatGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SatGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEquivAccess().getAlternatives_1_1(), "rule__Equiv__Alternatives_1_1");
			builder.put(grammarAccess.getImpliesAccess().getAlternatives_1_1(), "rule__Implies__Alternatives_1_1");
			builder.put(grammarAccess.getOrAccess().getAlternatives_1_1(), "rule__Or__Alternatives_1_1");
			builder.put(grammarAccess.getAndAccess().getAlternatives_1_1(), "rule__And__Alternatives_1_1");
			builder.put(grammarAccess.getNandAccess().getAlternatives_1_1(), "rule__Nand__Alternatives_1_1");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives_1_1(), "rule__Primary__Alternatives_1_1");
			builder.put(grammarAccess.getModelSATAccess().getGroup(), "rule__ModelSAT__Group__0");
			builder.put(grammarAccess.getModelSATAccess().getGroup_1(), "rule__ModelSAT__Group_1__0");
			builder.put(grammarAccess.getModelSATAccess().getGroup_1_1(), "rule__ModelSAT__Group_1_1__0");
			builder.put(grammarAccess.getEquivAccess().getGroup(), "rule__Equiv__Group__0");
			builder.put(grammarAccess.getEquivAccess().getGroup_1(), "rule__Equiv__Group_1__0");
			builder.put(grammarAccess.getImpliesAccess().getGroup(), "rule__Implies__Group__0");
			builder.put(grammarAccess.getImpliesAccess().getGroup_1(), "rule__Implies__Group_1__0");
			builder.put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
			builder.put(grammarAccess.getOrAccess().getGroup_1(), "rule__Or__Group_1__0");
			builder.put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
			builder.put(grammarAccess.getAndAccess().getGroup_1(), "rule__And__Group_1__0");
			builder.put(grammarAccess.getNandAccess().getGroup(), "rule__Nand__Group__0");
			builder.put(grammarAccess.getNandAccess().getGroup_1(), "rule__Nand__Group_1__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup(), "rule__Atomic__Group__0");
			builder.put(grammarAccess.getModelSATAccess().getExpressionAssignment_1_0(), "rule__ModelSAT__ExpressionAssignment_1_0");
			builder.put(grammarAccess.getModelSATAccess().getExpressionAssignment_1_1_1(), "rule__ModelSAT__ExpressionAssignment_1_1_1");
			builder.put(grammarAccess.getEquivAccess().getRhsAssignment_1_2(), "rule__Equiv__RhsAssignment_1_2");
			builder.put(grammarAccess.getImpliesAccess().getRhsAssignment_1_2(), "rule__Implies__RhsAssignment_1_2");
			builder.put(grammarAccess.getOrAccess().getRhsAssignment_1_2(), "rule__Or__RhsAssignment_1_2");
			builder.put(grammarAccess.getAndAccess().getRhsAssignment_1_2(), "rule__And__RhsAssignment_1_2");
			builder.put(grammarAccess.getNandAccess().getRhsAssignment_1_2(), "rule__Nand__RhsAssignment_1_2");
			builder.put(grammarAccess.getPrimaryAccess().getExpressionAssignment_1_2(), "rule__Primary__ExpressionAssignment_1_2");
			builder.put(grammarAccess.getAtomicAccess().getNameAssignment_1(), "rule__Atomic__NameAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SatGrammarAccess grammarAccess;

	@Override
	protected InternalSatParser createParser() {
		InternalSatParser result = new InternalSatParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SatGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SatGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
