/*
 * generated by Xtext 2.19.0
 */
package projetDSL.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import projetDSL.services.SATLGrammarAccess;

@SuppressWarnings("all")
public class SATLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SATLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_BooleanExpression_IDTerminalRuleCall_1_q;
	protected AbstractElementAlias match_NegOperatorExpression_NonKeyword_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SATLGrammarAccess) access;
		match_BooleanExpression_IDTerminalRuleCall_1_q = new TokenAlias(false, true, grammarAccess.getBooleanExpressionAccess().getIDTerminalRuleCall_1());
		match_NegOperatorExpression_NonKeyword_0_q = new TokenAlias(false, true, grammarAccess.getNegOperatorExpressionAccess().getNonKeyword_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_BooleanExpression_IDTerminalRuleCall_1_q.equals(syntax))
				emit_BooleanExpression_IDTerminalRuleCall_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_NegOperatorExpression_NonKeyword_0_q.equals(syntax))
				emit_NegOperatorExpression_NonKeyword_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ID?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Expression' (ambiguity) '{' expression+=BasicExpression
	 */
	protected void emit_BooleanExpression_IDTerminalRuleCall_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'non'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) negatedMember+=BasicExpression
	 */
	protected void emit_NegOperatorExpression_NonKeyword_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
