/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.GJ_MC_Tests;

import org.xtext.example.mydsl.GJ_MC_Process.ConjunctiveNormalForm;
import org.xtext.example.mydsl.GJ_MC_Process.SATUtils;
import org.xtext.example.mydsl.sat.Expression;
import org.xtext.example.mydsl.sat.Model;
import org.xtext.example.mydsl.tests.SatInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(SatInjectorProvider.class)
@SuppressWarnings("all")
public class SatCNFTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  @Test
  public void basicNotTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("solver sat4j-java");
      _builder.newLine();
      _builder.append("!A");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      final Expression cnf = ConjunctiveNormalForm.toCleanCNF(result.getExpression());
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("solver sat4j-java");
      _builder_1.newLine();
      _builder_1.append("!A");
      _builder_1.newLine();
      final Model oracle = this.parseHelper.parse(_builder_1);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_2.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_2.toString());
      Assertions.assertTrue(SATUtils.equals(cnf, oracle.getExpression()));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void basicOrTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("solver sat4j-java");
      _builder.newLine();
      _builder.append("A v B");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      final Expression cnf = ConjunctiveNormalForm.toCleanCNF(result.getExpression());
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("solver sat4j-java");
      _builder_1.newLine();
      _builder_1.append("A v B");
      _builder_1.newLine();
      final Model oracle = this.parseHelper.parse(_builder_1);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_2.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_2.toString());
      Assertions.assertTrue(SATUtils.equals(cnf, oracle.getExpression()));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void basicAndTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("solver sat4j-java");
      _builder.newLine();
      _builder.append("A ^ B");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      final Expression cnf = ConjunctiveNormalForm.toCleanCNF(result.getExpression());
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("solver sat4j-java");
      _builder_1.newLine();
      _builder_1.append("A ^ B");
      _builder_1.newLine();
      final Model oracle = this.parseHelper.parse(_builder_1);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_2.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_2.toString());
      Assertions.assertTrue(SATUtils.equals(cnf, oracle.getExpression()));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void basicDNFFormTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("solver sat4j-java");
      _builder.newLine();
      _builder.append("A ^ B v C ^ D");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      final Expression cnf = ConjunctiveNormalForm.toCleanCNF(result.getExpression());
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("solver sat4j-java");
      _builder_1.newLine();
      _builder_1.append("((A v C) ^ (A v D)) ^ ((B v C) ^ (B v D))");
      _builder_1.newLine();
      final Model oracle = this.parseHelper.parse(_builder_1);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_2.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_2.toString());
      Assertions.assertTrue(SATUtils.equals(cnf, oracle.getExpression()));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void basicCNFFormTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("solver sat4j-java");
      _builder.newLine();
      _builder.append("(A v B) ^ (C v D)");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      final Expression cnf = ConjunctiveNormalForm.toCleanCNF(result.getExpression());
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("solver sat4j-java");
      _builder_1.newLine();
      _builder_1.append("(A v B) ^ (C v D)");
      _builder_1.newLine();
      final Model oracle = this.parseHelper.parse(_builder_1);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_2.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_2.toString());
      Assertions.assertTrue(SATUtils.equals(cnf, oracle.getExpression()));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void ComplexExpressionTest() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("solver sat4j-java");
      _builder.newLine();
      _builder.append("!A v B ^ (!C v D) v E");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      final Expression cnf = ConjunctiveNormalForm.toCleanCNF(result.getExpression());
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("solver sat4j-java");
      _builder_1.newLine();
      _builder_1.append("(E v (!A v B)) ^ ((!A v !C) v (D v E))");
      _builder_1.newLine();
      final Model oracle = this.parseHelper.parse(_builder_1);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_2.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_2.toString());
      Assertions.assertTrue(SATUtils.equals(cnf, oracle.getExpression()));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
