/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalSattlParser;
import org.xtext.example.mydsl.services.SattlGrammarAccess;

public class SattlParser extends AbstractAntlrParser {

	@Inject
	private SattlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSattlParser createParser(XtextTokenStream stream) {
		return new InternalSattlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}

	public SattlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SattlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
