/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.satt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.satt.Sat#getSource <em>Source</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.satt.Sat#getCallMethod <em>Call Method</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.satt.SattPackage#getSat()
 * @model
 * @generated
 */
public interface Sat extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' containment reference.
   * @see #setSource(EObject)
   * @see org.xtext.example.mydsl.satt.SattPackage#getSat_Source()
   * @model containment="true"
   * @generated
   */
  EObject getSource();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.satt.Sat#getSource <em>Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' containment reference.
   * @see #getSource()
   * @generated
   */
  void setSource(EObject value);

  /**
   * Returns the value of the '<em><b>Call Method</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.satt.SATCallMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Call Method</em>' attribute.
   * @see org.xtext.example.mydsl.satt.SATCallMethod
   * @see #setCallMethod(SATCallMethod)
   * @see org.xtext.example.mydsl.satt.SattPackage#getSat_CallMethod()
   * @model
   * @generated
   */
  SATCallMethod getCallMethod();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.satt.Sat#getCallMethod <em>Call Method</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Call Method</em>' attribute.
   * @see org.xtext.example.mydsl.satt.SATCallMethod
   * @see #getCallMethod()
   * @generated
   */
  void setCallMethod(SATCallMethod value);

} // Sat
