/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.mSat;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SAT Morphic</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.mSat.SATMorphic#getSolvers <em>Solvers</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.mSat.SATMorphic#getBenchmark <em>Benchmark</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.mSat.MSatPackage#getSATMorphic()
 * @model
 * @generated
 */
public interface SATMorphic extends EObject
{
  /**
   * Returns the value of the '<em><b>Solvers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl1.mSat.SATSolver}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Solvers</em>' containment reference list.
   * @see org.xtext.example.mydsl1.mSat.MSatPackage#getSATMorphic_Solvers()
   * @model containment="true"
   * @generated
   */
  EList<SATSolver> getSolvers();

  /**
   * Returns the value of the '<em><b>Benchmark</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Benchmark</em>' containment reference.
   * @see #setBenchmark(Benchmark)
   * @see org.xtext.example.mydsl1.mSat.MSatPackage#getSATMorphic_Benchmark()
   * @model containment="true"
   * @generated
   */
  Benchmark getBenchmark();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.mSat.SATMorphic#getBenchmark <em>Benchmark</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Benchmark</em>' containment reference.
   * @see #getBenchmark()
   * @generated
   */
  void setBenchmark(Benchmark value);

} // SATMorphic
