<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sat" nsURI="m1sif.dsl" nsPrefix="m1sif.dsl">
  <eClassifiers xsi:type="ecore:EEnum" name="BinopType" instanceTypeName="BinopType">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="NAND" value="2"/>
    <eLiterals name="IMPLIES" value="3"/>
    <eLiterals name="BIIMPLIES" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnopType" instanceTypeName="UnopType">
    <eLiterals name="NOT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expressions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Exprs" upperBound="-1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Binop" abstract="true" interface="true"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Op" eType="#//BinopType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LeftParam" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RightParam" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unop" abstract="true" interface="true"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Op" eType="#//UnopType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Param" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
