/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MSatStandaloneSetup extends MSatStandaloneSetupGenerated {

	def static void doSetup() {
		new MSatStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
