/**
 * generated by Xtext 2.19.0
 */
package m2ccs.dsl.satsv.mydsl;

import m2ccs.dsl.satsv.mydsl.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
