/**
 * generated by Xtext 2.19.0
 */
package projetDSL.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Expressions System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetDSL.myDsl.BooleanExpressionsSystem#getBooleanExpressions <em>Boolean Expressions</em>}</li>
 * </ul>
 *
 * @see projetDSL.myDsl.MyDslPackage#getBooleanExpressionsSystem()
 * @model
 * @generated
 */
public interface BooleanExpressionsSystem extends EObject
{
  /**
   * Returns the value of the '<em><b>Boolean Expressions</b></em>' containment reference list.
   * The list contents are of type {@link projetDSL.myDsl.BooleanExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean Expressions</em>' containment reference list.
   * @see projetDSL.myDsl.MyDslPackage#getBooleanExpressionsSystem_BooleanExpressions()
   * @model containment="true"
   * @generated
   */
  EList<BooleanExpression> getBooleanExpressions();

} // BooleanExpressionsSystem
