/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalDimacsParser;
import org.xtext.example.mydsl.services.DimacsGrammarAccess;

public class DimacsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DimacsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DimacsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getLigneProblemeAccess().getGroup(), "rule__LigneProbleme__Group__0");
			builder.put(grammarAccess.getModelAccess().getLigneAssignment_0(), "rule__Model__LigneAssignment_0");
			builder.put(grammarAccess.getModelAccess().getClausesAssignment_2(), "rule__Model__ClausesAssignment_2");
			builder.put(grammarAccess.getLigneProblemeAccess().getNb_variablesAssignment_2(), "rule__LigneProbleme__Nb_variablesAssignment_2");
			builder.put(grammarAccess.getLigneProblemeAccess().getNb_clausesAssignment_3(), "rule__LigneProbleme__Nb_clausesAssignment_3");
			builder.put(grammarAccess.getLigneClauseAccess().getLitterauxAssignment(), "rule__LigneClause__LitterauxAssignment");
			builder.put(grammarAccess.getLitteralAccess().getValAssignment(), "rule__Litteral__ValAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DimacsGrammarAccess grammarAccess;

	@Override
	protected InternalDimacsParser createParser() {
		InternalDimacsParser result = new InternalDimacsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DimacsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DimacsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
