grammar org.xtext.example.mydsl.Dimacs with org.eclipse.xtext.common.Terminals

generate dimacs "http://www.xtext.org/example/mydsl/Dimacs"


CNF:
	comments+=Commentaire* '\n' problem+=LigneProbleme '\n' clauses+=LigneClause*	
;

Commentaire:
	'c' content=STRING '\n'
;
	
LigneProbleme:
	'p' 'cnf' nb_variables+=INT nb_clauses+=INT '\n'
;

LigneClause:
	litteraux+=litteral+ '0'
;

litteral : 
	val=INT
;
	