/**
 * generated by Xtext 2.19.0
 */
package m2ccs.dsl.satsv.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m2ccs.dsl.satsv.mydsl.myDsl.Formula#getVar <em>Var</em>}</li>
 *   <li>{@link m2ccs.dsl.satsv.mydsl.myDsl.Formula#getOp <em>Op</em>}</li>
 *   <li>{@link m2ccs.dsl.satsv.mydsl.myDsl.Formula#getArg <em>Arg</em>}</li>
 *   <li>{@link m2ccs.dsl.satsv.mydsl.myDsl.Formula#getArg1 <em>Arg1</em>}</li>
 *   <li>{@link m2ccs.dsl.satsv.mydsl.myDsl.Formula#getArg2 <em>Arg2</em>}</li>
 * </ul>
 *
 * @see m2ccs.dsl.satsv.mydsl.myDsl.MyDslPackage#getFormula()
 * @model
 * @generated
 */
public interface Formula extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference list.
   * The list contents are of type {@link m2ccs.dsl.satsv.mydsl.myDsl.Variable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference list.
   * @see m2ccs.dsl.satsv.mydsl.myDsl.MyDslPackage#getFormula_Var()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVar();

  /**
   * Returns the value of the '<em><b>Op</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' containment reference list.
   * @see m2ccs.dsl.satsv.mydsl.myDsl.MyDslPackage#getFormula_Op()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getOp();

  /**
   * Returns the value of the '<em><b>Arg</b></em>' containment reference list.
   * The list contents are of type {@link m2ccs.dsl.satsv.mydsl.myDsl.Formula}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' containment reference list.
   * @see m2ccs.dsl.satsv.mydsl.myDsl.MyDslPackage#getFormula_Arg()
   * @model containment="true"
   * @generated
   */
  EList<Formula> getArg();

  /**
   * Returns the value of the '<em><b>Arg1</b></em>' containment reference list.
   * The list contents are of type {@link m2ccs.dsl.satsv.mydsl.myDsl.Formula}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg1</em>' containment reference list.
   * @see m2ccs.dsl.satsv.mydsl.myDsl.MyDslPackage#getFormula_Arg1()
   * @model containment="true"
   * @generated
   */
  EList<Formula> getArg1();

  /**
   * Returns the value of the '<em><b>Arg2</b></em>' containment reference list.
   * The list contents are of type {@link m2ccs.dsl.satsv.mydsl.myDsl.Formula}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg2</em>' containment reference list.
   * @see m2ccs.dsl.satsv.mydsl.myDsl.MyDslPackage#getFormula_Arg2()
   * @model containment="true"
   * @generated
   */
  EList<Formula> getArg2();

} // Formula
