/**
 * generated by Xtext 2.19.0
 */
package m2ccs.dsl.satsv.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Un Op</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m2ccs.dsl.satsv.mydsl.myDsl.UnOp#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see m2ccs.dsl.satsv.mydsl.myDsl.MyDslPackage#getUnOp()
 * @model
 * @generated
 */
public interface UnOp extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see m2ccs.dsl.satsv.mydsl.myDsl.MyDslPackage#getUnOp_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link m2ccs.dsl.satsv.mydsl.myDsl.UnOp#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

} // UnOp
