<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sattl" nsURI="http://www.xtext.org/example/mydsl/Sattl" nsPrefix="sattl">
  <eClassifiers xsi:type="ecore:EClass" name="Formulae">
    <eStructuralFeatures xsi:type="ecore:EReference" name="form_left" upperBound="-1"
        eType="#//Formulae" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binop" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="form_right" upperBound="-1"
        eType="#//Formulae" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unop" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="form" upperBound="-1" eType="#//Formulae"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atom" upperBound="-1" eType="#//Atom"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
