/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.dimacs.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.dimacs.CNF;
import org.xtext.example.mydsl.dimacs.Commentaire;
import org.xtext.example.mydsl.dimacs.DimacsPackage;
import org.xtext.example.mydsl.dimacs.LigneClause;
import org.xtext.example.mydsl.dimacs.LigneProbleme;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>CNF</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.dimacs.impl.CNFImpl#getComments <em>Comments</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.dimacs.impl.CNFImpl#getProblem <em>Problem</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.dimacs.impl.CNFImpl#getClauses <em>Clauses</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CNFImpl extends MinimalEObjectImpl.Container implements CNF
{
  /**
   * The cached value of the '{@link #getComments() <em>Comments</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComments()
   * @generated
   * @ordered
   */
  protected EList<Commentaire> comments;

  /**
   * The cached value of the '{@link #getProblem() <em>Problem</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProblem()
   * @generated
   * @ordered
   */
  protected EList<LigneProbleme> problem;

  /**
   * The cached value of the '{@link #getClauses() <em>Clauses</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClauses()
   * @generated
   * @ordered
   */
  protected EList<LigneClause> clauses;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CNFImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DimacsPackage.Literals.CNF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Commentaire> getComments()
  {
    if (comments == null)
    {
      comments = new EObjectContainmentEList<Commentaire>(Commentaire.class, this, DimacsPackage.CNF__COMMENTS);
    }
    return comments;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LigneProbleme> getProblem()
  {
    if (problem == null)
    {
      problem = new EObjectContainmentEList<LigneProbleme>(LigneProbleme.class, this, DimacsPackage.CNF__PROBLEM);
    }
    return problem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LigneClause> getClauses()
  {
    if (clauses == null)
    {
      clauses = new EObjectContainmentEList<LigneClause>(LigneClause.class, this, DimacsPackage.CNF__CLAUSES);
    }
    return clauses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DimacsPackage.CNF__COMMENTS:
        return ((InternalEList<?>)getComments()).basicRemove(otherEnd, msgs);
      case DimacsPackage.CNF__PROBLEM:
        return ((InternalEList<?>)getProblem()).basicRemove(otherEnd, msgs);
      case DimacsPackage.CNF__CLAUSES:
        return ((InternalEList<?>)getClauses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DimacsPackage.CNF__COMMENTS:
        return getComments();
      case DimacsPackage.CNF__PROBLEM:
        return getProblem();
      case DimacsPackage.CNF__CLAUSES:
        return getClauses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DimacsPackage.CNF__COMMENTS:
        getComments().clear();
        getComments().addAll((Collection<? extends Commentaire>)newValue);
        return;
      case DimacsPackage.CNF__PROBLEM:
        getProblem().clear();
        getProblem().addAll((Collection<? extends LigneProbleme>)newValue);
        return;
      case DimacsPackage.CNF__CLAUSES:
        getClauses().clear();
        getClauses().addAll((Collection<? extends LigneClause>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DimacsPackage.CNF__COMMENTS:
        getComments().clear();
        return;
      case DimacsPackage.CNF__PROBLEM:
        getProblem().clear();
        return;
      case DimacsPackage.CNF__CLAUSES:
        getClauses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DimacsPackage.CNF__COMMENTS:
        return comments != null && !comments.isEmpty();
      case DimacsPackage.CNF__PROBLEM:
        return problem != null && !problem.isEmpty();
      case DimacsPackage.CNF__CLAUSES:
        return clauses != null && !clauses.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CNFImpl
