/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.dimacs.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.dimacs.DimacsPackage;
import org.xtext.example.mydsl.dimacs.LigneClause;
import org.xtext.example.mydsl.dimacs.LigneProbleme;
import org.xtext.example.mydsl.dimacs.Model;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.dimacs.impl.ModelImpl#getLigne <em>Ligne</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.dimacs.impl.ModelImpl#getClauses <em>Clauses</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getLigne() <em>Ligne</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLigne()
   * @generated
   * @ordered
   */
  protected EList<LigneProbleme> ligne;

  /**
   * The cached value of the '{@link #getClauses() <em>Clauses</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClauses()
   * @generated
   * @ordered
   */
  protected EList<LigneClause> clauses;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DimacsPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LigneProbleme> getLigne()
  {
    if (ligne == null)
    {
      ligne = new EObjectContainmentEList<LigneProbleme>(LigneProbleme.class, this, DimacsPackage.MODEL__LIGNE);
    }
    return ligne;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LigneClause> getClauses()
  {
    if (clauses == null)
    {
      clauses = new EObjectContainmentEList<LigneClause>(LigneClause.class, this, DimacsPackage.MODEL__CLAUSES);
    }
    return clauses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DimacsPackage.MODEL__LIGNE:
        return ((InternalEList<?>)getLigne()).basicRemove(otherEnd, msgs);
      case DimacsPackage.MODEL__CLAUSES:
        return ((InternalEList<?>)getClauses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DimacsPackage.MODEL__LIGNE:
        return getLigne();
      case DimacsPackage.MODEL__CLAUSES:
        return getClauses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DimacsPackage.MODEL__LIGNE:
        getLigne().clear();
        getLigne().addAll((Collection<? extends LigneProbleme>)newValue);
        return;
      case DimacsPackage.MODEL__CLAUSES:
        getClauses().clear();
        getClauses().addAll((Collection<? extends LigneClause>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DimacsPackage.MODEL__LIGNE:
        getLigne().clear();
        return;
      case DimacsPackage.MODEL__CLAUSES:
        getClauses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DimacsPackage.MODEL__LIGNE:
        return ligne != null && !ligne.isEmpty();
      case DimacsPackage.MODEL__CLAUSES:
        return clauses != null && !clauses.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
